print("Python Casting")
print("1. int(): Constructs an integer literal.")
x = int(1)
y = int(2.8)
z = int("3")
print(x)
print(y)
print(z)
print("2. float(): Constructs an float literal.")
a = float(1)
b = float(2.8)
c = float("3")
d = float("4.2")
print(a)
print(b)
print(c)
print(d)
print("3. str(): Constructs an string literal.")
m = str("s1")
n = str(2)
o = str(3.0)
print(m)
print(n)
print(o)